# Generated by Django 5.1.15 on 2026-04-20 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('alumni', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni_profile', to='students.student'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumnidonation',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='alumni.alumni'),
        ),
        migrations.AddField(
            model_name='alumnidonation',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='alumnieventattendee',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alumni.alumni'),
        ),
        migrations.AddField(
            model_name='alumnieventattendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='alumni.alumnievent'),
        ),
        migrations.AlterUniqueTogether(
            name='alumnieventattendee',
            unique_together={('event', 'alumni')},
        ),
    ]
