# Generated by Django 5.1.15 on 2026-04-20 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('scheme_type', models.CharField(choices=[('percentage', 'Percentage'), ('letter', 'Letter grade'), ('gpa', 'GPA')], max_length=16)),
                ('max_grade_points', models.DecimalField(blank=True, decimal_places=2, help_text='e.g., 10.00 for 10-point GPA', max_digits=4, null=True)),
                ('pass_threshold', models.DecimalField(decimal_places=2, help_text='Minimum percentage / grade_points to pass', max_digits=6)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradeConversionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('formula', models.CharField(help_text="e.g. 'CGPA * 9.5' (common 10-pt to percentage conversion)", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('from_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='grading.gradingscheme')),
                ('to_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='grading.gradingscheme')),
            ],
            options={
                'unique_together': {('from_scheme', 'to_scheme')},
            },
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('band_code', models.CharField(help_text='e.g. A+, A, First Class, 80-89', max_length=16)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grade_points', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_pass', models.BooleanField(default=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='grading.gradingscheme')),
            ],
            options={
                'ordering': ('scheme', '-min_percentage'),
                'unique_together': {('scheme', 'band_code')},
            },
        ),
    ]
