# Generated by Django 5.1.15 on 2026-04-20 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('employees', '0002_initial'),
        ('organization', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('hostel_type', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('coed', 'Co-ed')], max_length=16)),
                ('total_capacity', models.IntegerField(default=0)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostels', to='organization.campus')),
                ('warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warden_of', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostelApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='submitted', max_length=16)),
                ('remarks', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.academicyear')),
                ('preferred_hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='hostel.hostel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_applications', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostelBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64)),
                ('total_floors', models.SmallIntegerField(default=1)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='hostel.hostel')),
            ],
            options={
                'unique_together': {('hostel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HostelFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('floor_number', models.SmallIntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='hostel.hostelblock')),
            ],
            options={
                'unique_together': {('block', 'floor_number')},
            },
        ),
        migrations.CreateModel(
            name='HostelLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_leaves', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('room_no', models.CharField(max_length=32)),
                ('occupancy_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('dormitory', 'Dormitory')], default='double', max_length=16)),
                ('capacity', models.SmallIntegerField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostelfloor')),
            ],
            options={
                'unique_together': {('floor', 'room_no')},
            },
        ),
        migrations.CreateModel(
            name='HostelVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('visitor_name', models.CharField(max_length=200)),
                ('relation', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('id_proof', models.CharField(blank=True, max_length=64)),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in', 'In'), ('out', 'Out')], default='in', max_length=8)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('monthly_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contractor', models.CharField(blank=True, max_length=200)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messes', to='hostel.hostel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hostel.mess')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_bills', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('day_of_week', models.SmallIntegerField()),
                ('meal_type', models.CharField(help_text='breakfast/lunch/snacks/dinner', max_length=16)),
                ('items', models.TextField()),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='hostel.mess')),
            ],
            options={
                'unique_together': {('mess', 'day_of_week', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allocated_from', models.DateField()),
                ('allocated_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released')], default='active', max_length=16)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='hostel.hostelroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_allocations', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'status'], name='hostel_room_room_id_5d469a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student',), name='uniq_active_allocation_per_student')],
            },
        ),
    ]
