# Generated by Django 5.1.15 on 2026-04-20 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('vacancies', models.SmallIntegerField(default=1)),
                ('min_experience_years', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('opened_on', models.DateField()),
                ('closing_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('on_hold', 'On hold')], default='open', max_length=16)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='openings', to='organization.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='openings', to='employees.designation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('resume', models.FileField(blank=True, null=True, upload_to='recruitment/resumes/')),
                ('years_of_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('current_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interviewing', 'Interviewing'), ('offered', 'Offered'), ('rejected', 'Rejected'), ('joined', 'Joined'), ('withdrawn', 'Withdrawn')], default='applied', max_length=16)),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='recruitment.jobopening')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecruitmentInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('round_no', models.SmallIntegerField(default=1)),
                ('scheduled_at', models.DateTimeField()),
                ('feedback', models.TextField(blank=True)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('result', models.CharField(default='pending', max_length=16)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.jobapplicant')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecruitmentOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('offered_on', models.DateField()),
                ('ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='recruitment/offers/')),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('joined', 'Joined')], default='offered', max_length=16)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='recruitment.jobapplicant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
