# Generated by Django 5.1.15 on 2026-04-20 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('courses', '0001_initial'),
        ('employees', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.CharField(blank=True, max_length=64)),
                ('floor', models.SmallIntegerField(blank=True, null=True)),
                ('room_no', models.CharField(max_length=32)),
                ('room_type', models.CharField(choices=[('lecture_hall', 'Lecture Hall'), ('lab', 'Lab'), ('seminar', 'Seminar'), ('auditorium', 'Auditorium'), ('tutorial', 'Tutorial')], default='lecture_hall', max_length=16)),
                ('capacity', models.IntegerField(default=0)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='organization.campus')),
            ],
            options={
                'unique_together': {('campus', 'building', 'room_no')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('day_of_week', models.SmallIntegerField(help_text='0=Mon .. 6=Sun')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('name', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'ordering': ('day_of_week', 'start_time'),
                'unique_together': {('day_of_week', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='courses.courseoffering')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='timetable.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='academic.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='employees.employee')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='timetable.timeslot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('time_slot', 'teacher'), name='uniq_teacher_per_slot'), models.UniqueConstraint(fields=('time_slot', 'room'), name='uniq_room_per_slot'), models.UniqueConstraint(fields=('time_slot', 'section'), name='uniq_section_per_slot')],
            },
        ),
    ]
