# Generated by Django 5.1.15 on 2026-04-20 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('courses', '0001_initial'),
        ('employees', '0001_initial'),
        ('organization', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='organization.department'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='primary_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_offerings', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for', to='timetable.room'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='academic.section'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='academic.academicterm'),
        ),
        migrations.AddField(
            model_name='courseprerequisite',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq_links', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseprerequisite',
            name='prereq_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks_links', to='courses.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(related_name='required_for', through='courses.CoursePrerequisite', to='courses.course'),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_programs', to='courses.course'),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='academic.program'),
        ),
        migrations.AddField(
            model_name='syllabustopic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_topics', to='courses.course'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='courses.courseoffering'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['term', 'course'], name='courses_cou_term_id_4f26d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseprerequisite',
            unique_together={('course', 'prereq_course')},
        ),
        migrations.AlterUniqueTogether(
            name='programcourse',
            unique_together={('program', 'course', 'term_number')},
        ),
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together={('offering', 'employee', 'role')},
        ),
    ]
