# Generated by Django 5.1.15 on 2026-04-20 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('employees', '0001_initial'),
        ('grading', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='organization.department'),
        ),
        migrations.AddField(
            model_name='program',
            name='grading_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='grading.gradingscheme'),
        ),
        migrations.AddField(
            model_name='batch',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academic.program'),
        ),
        migrations.AddField(
            model_name='section',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academic.batch'),
        ),
        migrations.AddField(
            model_name='section',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_of', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='section',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academic.academicterm'),
        ),
        migrations.AlterUniqueTogether(
            name='academicterm',
            unique_together={('academic_year', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('department', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('program', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('batch', 'term', 'name')},
        ),
    ]
